package pyt.exception;

public class UnauthorizedException extends RuntimeException {

}
